baseURL = 'https://juniperspring.xyz'
languageCode = 'en-us'
title = 'Juniperspring'
theme = 'paper'

[module]
    [[module.imports]]
        path = "github.com/divinerites/plausible-hugo"

[params]
github = 'librick'
rss = true
name = 'Eric McDonald'
math = true

[params.plausible]
  enable = true  # Whether to enable plausible tracking
  domain = "juniperspring.xyz"  # Plausible "domain" name/id in your dashboard
