baseURL = 'https://juniperspring.xyz'
languageCode = 'en-us'
title = 'Juniperspring'
theme = 'paper'

[params]
github = 'librick'
rss = true
name = 'Eric McDonald'
math = true

[module]
   [[module.imports]]
   path = "github.com/divinerites/plausible-hugo"

[params.plausible]
enable = true
domain = "juniperspring.xyz"
gitstar = false
